language: generic

sudo: required

services:
    - docker

env:
    global:
        DOCKER_COMPOSE_VERSION: 1.10.0

before_install:
    - mkdir -p $HOME/bin
    - curl -s https://raw.githubusercontent.com/sagikazarmark/traviscripts/e106b6d593915a0cb736919ecb3804e8eb5e0440/scripts/glide.sh | bash
    - curl -L https://git.io/vMATh | sh
before_script: make setup
script: make INTEGRATION=true test cs
